{
  "openapi": "3.0.0",
  "info": {
    "title": "Api - Base",
    "description": "Documentação para a api base com as rotas para Administração, Estabelecimento e Clientes.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "description": "Local server",
      "url": "http://localhost:3000/api"
    },
    {
      "description": "Development server",
      "url": "https://dominioapi.com.br/api"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "tags": [
    {
      "name": "Administração"
    },
    {
      "name": "Estabelecimento"
    },
    {
      "name": "Cliente"
    }
  ],
  "paths": {
    "/admin/login": {
      "post": {
        "tags": [
          "Administração"
        ],
        "summary": "Login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "admin@teste.com",
                  "senha": "teste"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/estabelecimento/": {
      "post": {
        "tags": [
          "Estabelecimento"
        ],
        "summary": "Cadastrar Estabelecimento",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "nome": "Gomes",
                  "telefone": "48991300326",
                  "cpf": "00000000000",
                  "email": "estabelecimento@teste.com",
                  "senha": "teste",
                  "confirmarSenha": "teste"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": [
          "Estabelecimento"
        ],
        "summary": "Listar Estabelecimentos",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5AdGVzdGUuY29tIiwiaWF0IjoxNzI1OTE5OTExLCJleHAiOjE3MjYwMDYzMTF9.pTP1_0weFxUjPXsmMXzO29EJJC-2CJm7x0LjR8uAQu4"
          }
        ],
        
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Estabelecimento"
        ],
        "summary": "Deletar Estabelecimento",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/estabelecimento/2": {
      "put": {
        "tags": [
          "Estabelecimento"
        ],
        "summary": "Editar Estabelecimento",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "nome": "Gomes BarberShop",
                  "telefone": "48991300326",
                  "cpf": "00000000000",
                  "email": "estabelecimento@teste.com",
                  "senha": "teste",
                  "confirmarSenha": "teste"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/estabelecimento/login": {
      "post": {
        "tags": [
          "Estabelecimento"
        ],
        "summary": "Login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "estabelecimento@teste.com",
                  "senha": "teste"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/estabelecimento/3": {
      "get": {
        "tags": [
          "Estabelecimento"
        ],
        "summary": "Listar Estabelecimento pelo Id",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/cliente/": {
      "post": {
        "tags": [
          "Cliente"
        ],
        "summary": "Cadastrar Cliente",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "idEstabelecimento": 6,
                  "nome": "Cliente 1",
                  "telefone": "48991300326",
                  "email": "cliente@teste.com",
                  "senha": "teste",
                  "confirmarSenha": "teste"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": [
          "Cliente"
        ],
        "summary": "Listar Clientes",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImVtYWlsIjoiZXN0YWJlbGVjaW1lbnRvQHRlc3RlLmNvbSIsImlhdCI6MTcyNTkxOTkzNywiZXhwIjoxNzI2MDA2MzM3fQ.4mmEe2HqdoK2W_qdUTCpvBAdD4vM5TAx5IjwZwRewCI"
          },
          {
            "name": "auto",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Cliente"
        ],
        "summary": "Deletar Cliente",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/cliente/7": {
      "put": {
        "tags": [
          "Cliente"
        ],
        "summary": "Editar Cliente",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "nome": "Lex Luthor Dev",
                  "telefone": "48991300326",
                  "email": "cliente@teste.com"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": [
          "Cliente"
        ],
        "summary": "Listar Cliente pelo Id",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/cliente/login": {
      "post": {
        "tags": [
          "Cliente"
        ],
        "summary": "Login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "cliente@teste.com",
                  "senha": "teste"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/cliente/meus": {
      "get": {
        "tags": [
          "Cliente"
        ],
        "summary": "Listar Meus Clientes",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImVtYWlsIjoiZXN0YWJlbGVjaW1lbnRvQHRlc3RlLmNvbSIsImlhdCI6MTcyNTkxOTkzNywiZXhwIjoxNzI2MDA2MzM3fQ.4mmEe2HqdoK2W_qdUTCpvBAdD4vM5TAx5IjwZwRewCI"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  }
}